// Generated by https://quicktype.io

import { UserProfile } from "./user";

export interface Delivery {
    orderNumber:    number;
    address:        string;
    deliveryPerson: UserProfile | null;
    status:         string;
}
