// Generated by https://quicktype.io

import { Address, Position } from "./user";

export interface PostCodeResult {
    referencePosition?: Position;
    address:           Address;
    formattedAddress?:  string;
}
