// Generated by https://quicktype.io

import { UserDetail } from "./business";

export interface BusinessTransaction {
    amount:              number;
    fromUser:            FromUser;
    transactionStatus:   string;
    transactionDate:     string;
    transactionCurrency: string;
    transactionFee:      number;
}

export interface FromUser {
    email:      string;
    userDetail: UserDetail;
}
